export const newsData = [
    {
        contentBox3: '#ffffff',
        image34: '/assets/4f3ac76bf3b2d0bcd3e3ada9d465791b.png',
        text4: 'Kristin',
        text41: '19Dec, 2013',
        text42: '453',
        highlight2: 'Cras nisl dolor, accumsan et metus sit amet, vulputate condimentum dolor.',
        highlight3: 'Maecenas scelerisque, arcu quis tempus egestas, ligula diam molestie lectus, tincidunt malesuada arcu metus posuere metus.',
        btn: 'rgb(252 224 0)',
        btnText: 'Read more',
        link: '/news/1',
    },
    {
        contentBox3: '#ffffff',
        image34: '/assets/4f3ac76bf3b2d0bcd3e3ada9d465791b.png',
        text4: 'Kristin',
        text41: '19Dec, 2013',
        text42: '453',
        highlight2: 'Cras nisl dolor, accumsan et metus sit amet, vulputate condimentum dolor.',
        highlight3: 'Maecenas scelerisque, arcu quis tempus egestas, ligula diam molestie lectus, tincidunt malesuada arcu metus posuere metus.',
        btn: 'rgb(252 224 0)',
        btnText: 'Read more',
        link: '/news/1',
    },
    {
        contentBox3: '#ffffff',
        image34: '/assets/4f3ac76bf3b2d0bcd3e3ada9d465791b.png',
        text4: 'Kristin',
        text41: '19Dec, 2013',
        text42: '453',
        highlight2: 'Cras nisl dolor, accumsan et metus sit amet, vulputate condimentum dolor.',
        highlight3: 'Maecenas scelerisque, arcu quis tempus egestas, ligula diam molestie lectus, tincidunt malesuada arcu metus posuere metus.',
        btn: 'rgb(252 224 0)',
        btnText: 'Read more',
        link: '/news/1',
    },
    {
        contentBox3: '#ffffff',
        image34: '/assets/4f3ac76bf3b2d0bcd3e3ada9d465791b.png',
        text4: 'Kristin',
        text41: '19Dec, 2013',
        text42: '453',
        highlight2: 'Cras nisl dolor, accumsan et metus sit amet, vulputate condimentum dolor.',
        highlight3: 'Maecenas scelerisque, arcu quis tempus egestas, ligula diam molestie lectus, tincidunt malesuada arcu metus posuere metus.',
        btn: 'rgb(252 224 0)',
        btnText: 'Read more',
        link: '/news/1',
    },
    {
        contentBox3: '#ffffff',
        image34: '/assets/4f3ac76bf3b2d0bcd3e3ada9d465791b.png',
        text4: 'Kristin',
        text41: '19Dec, 2013',
        text42: '453',
        highlight2: 'Cras nisl dolor, accumsan et metus sit amet, vulputate condimentum dolor.',
        highlight3: 'Maecenas scelerisque, arcu quis tempus egestas, ligula diam molestie lectus, tincidunt malesuada arcu metus posuere metus.',
        btn: 'rgb(252 224 0)',
        btnText: 'Read more',
        link: '/news/1',
    },
    // Можно добавить больше карточек, если нужно
];

export default newsData